name: CI/CD scelet            

on:
  push:
    branches:
      - main
      - dev*
      - feature*
      - fix*

env:
  GO111MODULE: "on"       

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.21

      - name: Check out code
        uses: actions/checkout@v4

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2